#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(FOCUS_PUNCH) \
    F(DRAGON_CLAW) \
    F(WATER_PULSE) \
    F(CALM_MIND) \
    F(ROAR) \
    F(TOXIC) \
    F(HAIL) \
    F(BULK_UP) \
    F(BULLET_SEED) \
    F(HIDDEN_POWER) \
    F(SUNNY_DAY) \
    F(TAUNT) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(HYPER_BEAM) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(RAIN_DANCE) \
    F(GIGA_DRAIN) \
    F(SAFEGUARD) \
    F(FRUSTRATION) \
    F(SOLAR_BEAM) \
    F(IRON_TAIL) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(EARTHQUAKE) \
    F(RETURN) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(DOUBLE_TEAM) \
    F(REFLECT) \
    F(SHOCK_WAVE) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(SANDSTORM) \
    F(FIRE_BLAST) \
    F(ROCK_TOMB) \
    F(AERIAL_ACE) \
    F(TORMENT) \
    F(FACADE) \
    F(SECRET_POWER) \
    F(REST) \
    F(ATTRACT) \
    F(THIEF) \
    F(STEEL_WING) \
    F(SKILL_SWAP) \
    F(SNATCH) \
    F(OVERHEAT) \
	F(DOUBLE_EDGE) \
	F(DYNAMIC_PUNCH) \
	F(EXPLOSION) \
	F(FURY_CUTTER) \
	F(METRONOME) \
	F(MIMIC) \
	F(ROLLOUT) \
	F(SLEEP_TALK) \
	F(SUBSTITUTE) \
	F(SWAGGER) \
	F(SOFTBOILED) \
	F(SEISMIC_TOSS) \
	F(DREAM_EATER) \
	F(MEGA_PUNCH) \
	F(MEGA_KICK) \
	F(BODY_SLAM) \
	F(ROCK_SLIDE) \
	F(COUNTER) \
	F(THUNDER_WAVE) \
	F(SWORDS_DANCE) \
	F(DEFENSE_CURL) \
	F(SNORE) \
	F(MUD_SLAP) \
	F(SWIFT) \
	F(ICY_WIND) \
	F(ENDURE) \
	F(PSYCH_UP) \
	F(ICE_PUNCH) \
	F(THUNDER_PUNCH) \
	F(FIRE_PUNCH) \
	F(SELFDESTRUCT)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
